name: WingShopCoin
main: Angga7Togk\Store\WingShop
version: 1.0.0
api: 4.0.0
author: YukariAst

commands:
  wingshop:
    description: "open wingshop menu"
    permission: wingshop.command
    aliases: [ws]

permissions:
  wingshop.command:
    default: true
